



const getUsers = async (req, res) => {
        try {
                
        } catch (error) {
                
        }
        }